Verbeteringen aan TOKEN

diff --git a/TOKEN b/TOKEN
--- a/TOKEN
+++ b/TOKEN
@@ -1,7 +1,12 @@
 #!/bin/bash
 
-VERSION="0.13"
+VERSION="0.20"
 MYBASENAME=$(basename "$0")
+
+char1=$'\x01'
+char2=$'\x02'
+char3=$'\x03'
+stopper="${char1}${char2}${char3}${char2}${char1}"
 
 show_usage() {
     cat << EOF
@@ -60,7 +65,17 @@ TOKEN() {
     # Split de string op delimiter
     local tokens=()
     
-    mapfile -d "$delimiter"  -t tokens <<< "$haystack"
+    mapfile -d "$delimiter"  -t tokens <<< "$haystack""bla"
+    
+    # Na het splitten, 
+    if [ "${#tokens[@]}" -gt 0 ]; then
+      last=${#tokens[@]}-1
+      if [ "${tokens[$last]: -3}" = "bla" ]; then
+        tokens[$last]="${tokens[$last]%???}"  # Verwijder laatste 3 karakters
+      else
+        tokens[$last]="${tokens[$last]%????}"  # Verwijder laatste 4 karakters
+      fi
+    fi
     
     # Bereken de effectieve index
     local index
@@ -86,33 +101,105 @@ TOKEN() {
 args=()
 
 # Check voor pipe input
-if [ ! -t 0 ]; then
-    # Lees ALLE stdin met de nieuwe methode (behoudt newlines!)
-    stdin_content=$(cat; echo bla)
-    stdin_content="${stdin_content::-4}"
-    if [ -n "$stdin_content" ]; then
+if read -t 0 -n 0; then
+    stdin_content=$(cat; echo "$stopper")
+    if [ "${#stdin_content}" -gt "5" ] ;then
+      stdin_content="${stdin_content::-6}"
+      if [ -n "$stdin_content" ]; then
         args+=("$stdin_content")
+      fi
     fi
 fi
 
-# Voeg command line argumenten toe, maar behandel -- speciaal
+debug=""
+verbose=""
+dryrun=""
+silent=""
+endofoptions=""
 for arg in "$@"; do
     case "$arg" in
-        -h|--help)
         
-            show_usage
-            exit 0
+        -h|--help)
+            
+            if [ -z "$endofoptions" ]; then
+              show_usage
+              exit 0
+            fi
+            args+=("$arg")
             ;;
+        
         -v|--version)
-            echo "$VERSION"
-            exit 0
+            if [ -z "$endofoptions" ]; then
+              echo "$VERSION"
+              exit 0
+            fi
+            args+=("$arg")
             ;;
-       
-        *)
+           
+        -d|--debug)
+            if [ -z "$endofoptions" ]; then
+              debug="1"
+            else
+              args+=("$arg")
+            fi
+            ;;
+        
+        --verbose)
+            if [ -z "$endofoptions" ]; then
+              verbose="1"
+            else
+              args+=("$arg")
+            fi
+            ;;
+        
+        --dryrun)
+            if [ -z "$endofoptions" ]; then
+              dryrun="1"
+            else
+              args+=("$arg")
+            fi
+            ;;
+        
+        -s|--silent)
+            if [ -z "$endofoptions" = "0" ]; then
+              silent="1"
+            else
+              args+=("$arg")
+            fi
+            ;;
+        
+        
+        --)
+            if [ -z "$endofoptions" ]; then
+              shift
+              endofoptions="1"  
+            else
+              args+=("$arg")
+            fi
+            ;;
+                
+        -*)
+            if [ -z "$endofoptions" ]; then
+              args+=("$arg")
+            else
+              echo "ERROR: Unknown option $arg" >&2
+              show_usage
+              exit 123
+            fi
+            ;;
+          
+        *) 
             args+=("$arg")
             ;;
     esac
 done
+
+# Check bash versie (mapfile bestaat sinds bash 4.0)
+if [ "${BASH_VERSINFO[0]}" -lt 4 ]; then
+  echo "Warning: Your bash version is ${BASH_VERSINFO[0]}.${BASH_VERSINFO[1]}" >&2
+  echo "mapfile needs bash 4.0 or higher. Upgrade bash for full support." >&2
+  exit 123
+fi
 
 # Valideer aantal argumenten
 if [ "${#args[@]}" -lt 2 ]; then
